<?php die(); ?><!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Lỗi cơ sở dữ liệu</title>

</head>
<body>
	<h1>Lỗi kết nối tới cơ sở dữ liệu</h1>
</body>
</html>

<!-- Dynamic page generated in 29.302 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-08-02 07:35:28 -->
